# Generated by Django 6.0.2 on 2026-04-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
